CREATE DATABASE NETFLIX_PROJECT;
USE  NETFLIX_PROJECT;

DROP TABLE IF EXISTS NETFLIX;
CREATE TABLE NETFLIX
(
    SHOW_ID      VARCHAR(5),
    TYPE         VARCHAR(10),
    TITLE        VARCHAR(250),
    DIRECTOR     VARCHAR(550),
    CASTS        VARCHAR(1050),
    COUNTRY      VARCHAR(550),
    DATE_ADDED   VARCHAR(55),
    RELEASE_YEAR INT,
    RATING       VARCHAR(15),
    DURATION     VARCHAR(15),
    LISTED_IN    VARCHAR(250),
    DESCRIPTION  VARCHAR(550)
);

SELECT * FROM NETFLIX;

---Data Cleaning--Replacing Null Value with 'UNKNOWN'
SELECT * 
FROM NETFLIX 
WHERE DIRECTOR IS NULL 
OR COUNTRY IS NULL
OR TYPE IS NULL
OR CASTS IS NULL
OR RELEASE_YEAR IS NULL
OR RATING IS NULL
OR DURATION IS NULL
OR LISTED_IN IS NULL
OR DESCRIPTION IS NULL;


UPDATE NETFLIX 
SET DIRECTOR = 'UNKNOWN'
WHERE DIRECTOR IS NULL;
UPDATE NETFLIX 
SET COUNTRY = 'UNKNOWN'
WHERE COUNTRY IS NULL;
UPDATE NETFLIX 
SET CASTS = 'UNKNOWN'
WHERE CASTS IS NULL;
UPDATE NETFLIX 
SET RATING = 'UNKNOWN'
WHERE RATING IS NULL;
UPDATE NETFLIX 
SET DURATION = 'UNKNOWN'
WHERE DURATION IS NULL;
UPDATE NETFLIX 
SET DESCRIPTION = 'UNKNOWN'
WHERE DESCRIPTION IS NULL

ALTER TABLE NETFLIX
ALTER COLUMN date_added TYPE DATE
USING TO_DATE(date_added, 'Month DD, YYYY');
 
SELECT * FROM NETFLIX;
---Count the Number of Movies vs TV Shows

SELECT TYPE, COUNT(*)
FROM NETFLIX
GROUP BY TYPE;

--Find the Most Common Rating for Movies and TV Shows

WITH A
AS(
SELECT RATING, 
TYPE, 
COUNT(*) AS RATING_COUNT
FROM NETFLIX
GROUP BY RATING,TYPE),
RANKING
AS(
SELECT 
RATING, TYPE,
DENSE_RANK () OVER (PARTITION BY TYPE ORDER BY RATING_COUNT DESC) AS R
FROM A)
SELECT 
RATING AS "COMMON_RATING"
,TYPE
FROM RANKING
WHERE R = 1
;

---List All Movies Released in a Specific Year (e.g., 2020)
SELECT *, RELEASE_YEAR
FROM NETFLIX
WHERE TYPE = 'Movie' AND RELEASE_YEAR= 2020;

---Find the Top 5 Countries with the Most Content on Netflix
SELECT COUNTRY, COUNT(*)
FROM NETFLIX
WHERE COUNTRY != 'UNKNOWN'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

---Find Content Added in the Last 5 Years
SELECT *
FROM NETFLIX
WHERE DATE_ADDED > CURRENT_DATE - INTERVAL '5 YEARS'
ORDER BY DATE_ADDED DESC;

---Find All Movies/TV Shows by Director 'Rajiv Chilaka'
SELECT * 
FROM NETFLIX
WHERE DIRECTOR LIKE '%Rajiv Chilaka%';

---List All TV Shows with More Than 5 Seasons
SELECT *
FROM NETFLIX
WHERE TYPE = 'TV Show' AND
SPLIT_PART(DURATION,' ',1)::INT > 5
ORDER BY SPLIT_PART(DURATION,' ',1)::INT > 5 DESC;

---Count the Number of Content Items in Each Genre
SELECT 
UNNEST(STRING_TO_ARRAY(LISTED_IN,',')),
COUNT(*)
FROM NETFLIX
GROUP BY 1
ORDER BY 2 DESC;

---Find each year and the average numbers of content release in India per month on netflix.
SELECT RELEASE_YEAR,
COUNT(SHOW_ID),
ROUND(COUNT(SHOW_ID)::NUMERIC/12,2)
FROM NETFLIX
WHERE COUNTRY ILIKE '%INDIA%'
GROUP BY 1
ORDER BY 2 DESC;

---List All Movies that are Documentaries
SELECT *
FROM NETFLIX
WHERE TYPE = 'Movie' AND
LISTED_IN ILIKE '%DOCUMENTARIES%';

---Find All Content Without a Director
SELECT *
FROM NETFLIX
WHERE DIRECTOR = 'UNKNOWN';

--- Find How Many Movies Actor 'Salman Khan' Appeared in the Last 10 Years
SELECT *
FROM NETFLIX
WHERE TYPE = 'Movie' AND
CASTS ILIKE '%SALMAN KHAN%' AND
RELEASE_YEAR > EXTRACT(YEAR FROM CURRENT_DATE) - 10;

---Find the Top 10 Actors Who Have Appeared in the Highest Number of Movies Produced in India
SELECT
ACTOR,
COUNT(*) FROM
(SELECT
COUNTRY,
TYPE,
TRIM(UNNEST(STRING_TO_ARRAY(CASTS,','))) AS ACTOR
FROM NETFLIX)
WHERE COUNTRY ILIKE '%INDIA%' AND
TYPE = 'Movie' AND
ACTOR != 'UNKNOWN'
GROUP BY 1
ORDER BY 2 DESC LIMIT 10;

---Categorize Content Based on the Presence of 'Kill' and 'Violence' Keywords
SELECT CATEGORY,COUNT(*)
FROM
(SELECT
 CASE
  WHEN DESCRIPTION ILIKE '%KILL%' OR DESCRIPTION ILIKE '%VIOLENCE%' THEN 'BAD'
  ELSE 'GOOD'
  END AS CATEGORY
  FROM NETFLIX) AS CATEGORIZE_DATA
  GROUP BY CATEGORY;